#main
font=JetBrains Mono Nerd Font:size=15
prompt="> "
icons-enabled=yes
icon-theme=Papirus-Dark
fields=name,generic,comment,categories,filename,keywords
show-actions=yes
lines=7
width=35
horizontal-pad=20
vertical-pad=12
inner-pad=8
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=1c1614ee
text=f2ece4ff
match=d48f43ff
selection=3d2e28ff
selection-text=f2ece4ff
selection-match=ffb054ff
border=8c6946ff
prompt=8c6946ff

[border]
width=2
radius=12