# ────────────────────────────────────────────────────────────
# Omarchy Theme for Hyprland
# ────────────────────────────────────────────────────────────

general {
    col.active_border = rgb(B3B4B4)
    col.inactive_border = rgb(2B2C2B)
    border_size = 2
    gaps_in = 2
    gaps_out = 4
}

animations {
    enabled = yes

    bezier = easeSoft, 0.18, 0.62, 0.32, 1.00
    bezier = easeFade, 0.28, 0.00, 0.22, 1.00

    animation = windows,          1, 2.6, easeSoft
    animation = windowsIn,        1, 2.4, easeSoft
    animation = windowsOut,       1, 2.2, easeFade
    animation = windowsMove,      1, 2.8, easeSoft

    animation = fade,             1, 2.2, easeFade
    animation = fadeIn,           1, 2.0, easeSoft
    animation = fadeOut,          1, 1.8, easeFade
    animation = fadeDim,          1, 1.8, easeFade

    animation = layers,           1, 2.2, easeSoft
    animation = layersIn,         1, 2.0, easeSoft
    animation = layersOut,        1, 1.8, easeFade

    animation = workspaces,       1, 2.4, easeSoft
    animation = specialWorkspace, 1, 2.2, easeSoft

    animation = border,           1, 2.8, easeSoft
    animation = borderangle,      1, 3.0, easeSoft
    animation = fadeSwitch,       1, 1.4, easeFade
}


decoration {
    rounding = 12
    shadow {
        enabled = false
        range = 15
        render_power = 5
        offset = 0 0
    } 
    
blur {
    enabled = true
    size = 2         
    passes = 4
    contrast = 1.1
    brightness = 1.1
    vibrancy = 0.2    
    vibrancy_darkness = 0.2
    noise = 0.03      
    ignore_opacity = true
    new_optimizations = on
}
    active_opacity = 0.98
    inactive_opacity = 0.92
    fullscreen_opacity = 1.0 
}


layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0
  match:namespace = walker
}

layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0.1
  match:namespace = waybar
}

layerrule {
  name = layerrule-3
  blur = on
  ignore_alpha = 0.2
  match:namespace = mako
}

layerrule {
  name = layerrule-4
  blur = on
  ignore_alpha = 0.1
  match:namespace = vicinae
}

layerrule {
  name = layerrule-5
  blur = on
  match:namespace = swayosd
}

