# Extra autostart processes
exec-once = waybar
exec-once = waypaper --restore
# exec-once = uwsm-app -- my-service
#exec-once = hyprctl setcursor MacTahoe-cursors 24
#exec-once = uwsm-app -- hyprctl setcursor MacTahoe-cursors 24
#exec = hyprctl hyprpaper wallpaper ", ~/.config/Wallpaper/arch-nord-light.png"
#1
exec-once = [workspace 1 silent] kitty -e cava
exec-once = [workspace 1 silent] kitty -e cmatrix -C white
exec-once = [workspace 1 silent] com.spotify.Client
exec-once = [workspace 1 silent] kitty -e tty-clock -C 6 -b -c




#2
exec-once = [workspace 2 silent ] kitty
#coding
#exec-once = [workspace 2 silent] io.github.shiftey.Desktop


#3



exec-once = [workspace 3 silent] zen-browser



#4