# Application 
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# Add extra bindings
bind = SUPER, Q, exec,kitty
bind = SUPER, C, exec,google-chrome-beta
bind = ALT, 1, movetoworkspace, 1
bind = ALT, 2, movetoworkspace, 2
bind = ALT, 3, movetoworkspace, 3
bind = ALT, 4, movetoworkspace, 4
bind = AlT, 5, movetoworkspace, 5

# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
unbind = SUPER, SPACE
# Bind standalone Super key to Rofi drun
bindr = SUPER, Super_L, exec, killall fuzzel || fuzzel
bindr = SUPER, SPACE, exec ,fuzzel --dmenu --lines 0 --placeholder "Google Search" | xargs -I {} xdg-open "https://google.com/search?q={}"

# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
