# Application 
$mainMod = SUPER


bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"




bind = $mainMod SHIFT,S , exec, hyprshot -m region
bind = SUPER, F, fullscreen
bind = SUPER, W, killactive
bind = SUPER, Q, exec,kitty
bind = SUPER, C, exec,google-chrome
#workspace
bind = ALT, 1, movetoworkspace, 1
bind = ALT, 2, movetoworkspace, 2
bind = ALT, 3, movetoworkspace, 3
bind = ALT, 4, movetoworkspace, 4
bind = AlT, 5, movetoworkspace, 5
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6

#window
bindm = SUPER, mouse:273, resizewindow
bindm = SUPER, mouse:272, movewindow
# bindd = SUPER SHIFT, R, exec, alacritty -e ssh your-server

bind = SUPER SHIFT, space, exec, killall -SIGUSR1 waybar


#Bind fuzzel
bindr = SUPER, Super_L, exec, killall fuzzel || fuzzel\
#fuzzel google
bindr = SUPER, SPACE, exec ,fuzzel --dmenu --lines 0 --placeholder "Google Search" | xargs -I {} xdg-open "https://google.com/search?q={}"

# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
