env = XCURSOR_THEME,Tahoe-Cursor
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GTK_THEME,Adwaita:dark


#Wallpaper

#exec-once = hyprctl hyprpaper wallpaper ", ~/.config/Wallpaper/old.jpg"
misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true 
    disable_hyprland_logo = true
    disable_watchdog_warning = true
    disable_splash_rendering = true
}

splash = false

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
exec-once = hyprpaper

# Toggle config flags dynamically
#source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
#
#exec-once = hyprpaper
#exec-once = hyprctl hyprpaper preload "~/.config/hypr/background.png" && hyprctl hyprpaper wallpaper ", ~/.config/hypr/background.png"
workspace = 6, monitor:HEADLESS-2, default:true(No spaces around the equals sign)
env = XCURSOR_THEME,Tahoe-Cursor
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GTK_THEME,Adwaita:dark


#Wallpaper

#exec-once = hyprctl hyprpaper wallpaper ", ~/.config/Wallpaper/old.jpg"
misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true 
    disable_hyprland_logo = true
    disable_watchdog_warning = true
    disable_splash_rendering = true
}

splash = false

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
exec-once = hyprpaper

# Toggle config flags dynamically
#source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
#
#exec-once = hyprpaper
#exec-once = hyprctl hyprpaper preload "~/.config/hypr/background.png" && hyprctl hyprpaper wallpaper ", ~/.config/hypr/background.png"
workspace = 6, monitor:HEADLESS-2, default:true
