splash = false

preload = ~/.config/hypr/background.png
wallpaper = DP-1, ~/.config/hypr/background.png



#exec-once = hyprctl hyprpaper wallpaper ", ~/.config/hypr/background.png"

splash = false
disable_hyprland_logo = true 
disable_splash_rendering = true
